index.html
Nhix007/Path2Tech-Capstone-Project pull request #3
Opened 2024-06-20 20:19 UTC by codinggeek29

please review code.

2024-06-21 01:38 UTC, Nhix007 requested changes
Please make edits to lines 10 & 71

2024-06-26 01:39 UTC, Anwatts2 commented on index.html
> +        <p class="sub-text2 footer-hashen">A Web Solution by TechSheroes.</p>
footer-TechSheroes

2024-06-26 01:40 UTC, codinggeek29 commented on index.html
> +        <p class="sub-text2 footer-hashen">A Web Solution by TechSheroes.</p>
done

2024-06-26 01:43 UTC, Anwatts2 approved these changes

2024-06-26 01:47 UTC, Nhix007 approved these changes

2024-06-26 01:47 UTC, merged